window.CALENDAR_DATA={
  "asof": "2026-09-17",
  "companies": [
    {
      "id": "talent",
      "name": "Talent Labo",
      "label": "オルディナパートナーズ",
      "color": "#266b54",
      "url": "https://talentlabo.jp/"
    },
    {
      "id": "deiba",
      "name": "DEiBA Company",
      "label": "デアイバ",
      "color": "#4264b0",
      "url": "https://deiba.jp/event/event"
    },
    {
      "id": "cheer",
      "name": "チアキャリア",
      "label": "チアフェス",
      "color": "#b36a20",
      "url": "https://cheercareer.jp/lp/cheer_fes"
    },
    {
      "id": "shabell",
      "name": "しゃべる",
      "label": "しゃべる就活・フェスタ",
      "color": "#906080",
      "url": "https://event.shabell.co.jp/"
    },
    {
      "id": "meshi",
      "name": "社長メシ",
      "label": "運営・掲載企業のイベント",
      "color": "#b95649",
      "url": "https://app.shachomeshi.com/"
    },
    {
      "id": "jobtv",
      "name": "JOBTV",
      "label": "Arena・Summit・Draft・Fes",
      "color": "#387f91",
      "url": "https://media.jobtv.jp/service/recruitment-event#events"
    }
  ],
  "events": [
    {
      "date": "2026-09-16",
      "company": "deiba",
      "title": "就活の軸を言語化する 自己分析セミナー",
      "area": "未確認",
      "venue": "形式・会場 n.a.",
      "time": "15:00～16:00",
      "status": "公式",
      "note": "本日分：依頼時点で終了時刻経過。",
      "source": "https://deiba.jp/event/event#category2-block1-event1",
      "host": "DEiBA Company",
      "id": "evt-001"
    },
    {
      "date": "2026-09-16",
      "company": "deiba",
      "title": "コンサル内定者直伝！グルディスにも使えるケース面接対策セミナー",
      "area": "未確認",
      "venue": "形式・会場 n.a.",
      "time": "18:00～19:00",
      "status": "公式",
      "note": "本日分：依頼時点で終了時刻経過。",
      "source": "https://deiba.jp/event/event#category2-block1-event2",
      "host": "DEiBA Company",
      "id": "evt-002"
    },
    {
      "date": "2026-09-17",
      "company": "deiba",
      "title": "グルディスで何をすればいい？ 初心者向け対策セミナー",
      "area": "未確認",
      "venue": "形式・会場 n.a.",
      "time": "15:00～16:00",
      "status": "公式",
      "note": "",
      "source": "https://deiba.jp/event/event#category2-block1-event3",
      "host": "DEiBA Company",
      "id": "evt-003"
    },
    {
      "date": "2026-09-18",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "東京",
      "venue": "東京",
      "time": "10:00～14:00／15:30～19:30",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。 直近予約フォームでも時間を確認。事前セミナー等の集合時刻は別途確認。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-004"
    },
    {
      "date": "2026-09-24",
      "company": "meshi",
      "title": "300億企業の役員と語る、最速のキャリア戦略",
      "area": "東京",
      "venue": "東京・渋谷または恵比寿",
      "time": "18:00～20:00",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/3amY20BXkx",
      "host": "TAPP",
      "id": "evt-005"
    },
    {
      "date": "2026-09-25",
      "company": "deiba",
      "title": "28卒｜インターンシップ選考対策講座～面接対策～",
      "area": "未確認",
      "venue": "形式・会場 n.a.",
      "time": "15:00～16:00",
      "status": "公式",
      "note": "",
      "source": "https://deiba.jp/event/event#category2-block1-event4",
      "host": "DEiBA Company",
      "id": "evt-006"
    },
    {
      "date": "2026-09-25",
      "company": "meshi",
      "title": "経営・事業責任者直下｜マーケティングで事業を伸ばす長期インターン",
      "area": "東京",
      "venue": "東京・五反田駅周辺",
      "time": "18:30～20:30",
      "status": "他社主催",
      "note": "全学年。自社インターン採用の食事会。社長メシ掲載。",
      "source": "https://app.shachomeshi.com/event-detail/zcoOePDE5H",
      "host": "Maenomery",
      "id": "evt-007"
    },
    {
      "date": "2026-09-25",
      "company": "meshi",
      "title": "現学生から10年後に日本のリーダーを創出していく",
      "area": "東京",
      "venue": "東京・人形町",
      "time": "19:00～21:00",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/Bo5p0OhtUc",
      "host": "MINZCREW",
      "id": "evt-008"
    },
    {
      "date": "2026-09-26",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "東京",
      "venue": "東京",
      "time": "11:20～17:20",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-009"
    },
    {
      "date": "2026-09-26",
      "company": "cheer",
      "title": "チアフェス",
      "area": "東京",
      "venue": "東京",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-010"
    },
    {
      "date": "2026-09-26",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "東京",
      "venue": "東京・AP渋谷道玄坂11F",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-011"
    },
    {
      "date": "2026-09-26",
      "company": "talent",
      "title": "Talent Labo｜対面・少人数座談会",
      "area": "東京",
      "venue": "東京都渋谷区円山町3-6 E・スペースタワー6F",
      "time": "14:00～17:30",
      "status": "公式",
      "note": "28卒限定。受付 13:30～。公式LPおよび参加希望日程フォームで確認。",
      "source": "https://talentlabo.jp/form.html",
      "host": "Talent Labo（ご指定：オルディナパートナーズ）",
      "id": "evt-012"
    },
    {
      "date": "2026-09-27",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "名古屋",
      "venue": "名古屋",
      "time": "11:20～17:00",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-013"
    },
    {
      "date": "2026-09-28",
      "company": "meshi",
      "title": "20代で経営を動かす",
      "area": "東京",
      "venue": "東京・銀座・本社",
      "time": "19:00～21:00",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/xCtHi3uCFx",
      "host": "EXIDEA",
      "id": "evt-014"
    },
    {
      "date": "2026-09-28",
      "company": "meshi",
      "title": "選考直結型｜勝てる営業力について社長自ら伝授",
      "area": "東京",
      "venue": "東京・麻布十番",
      "time": "19:00～21:00",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/CnsuMQQ4c8",
      "host": "TRY GREEN",
      "id": "evt-015"
    },
    {
      "date": "2026-09-29",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "東京",
      "venue": "東京",
      "time": "10:00～14:00／15:30～19:30",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。 直近予約フォームでも時間を確認。事前セミナー等の集合時刻は別途確認。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-016"
    },
    {
      "date": "2026-09-29",
      "company": "deiba",
      "title": "企業選びの軸をつくる 業界・企業研究セミナー",
      "area": "未確認",
      "venue": "形式・会場 n.a.",
      "time": "15:00～16:00",
      "status": "公式",
      "note": "",
      "source": "https://deiba.jp/event/event#category2-block1-event5",
      "host": "DEiBA Company",
      "id": "evt-017"
    },
    {
      "date": "2026-09-29",
      "company": "meshi",
      "title": "27卒28卒｜内定まで2週間・スピード選考",
      "area": "東京",
      "venue": "東京本社",
      "time": "18:00～20:00",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/x6SzJZsHJH",
      "host": "イヴレス",
      "id": "evt-018"
    },
    {
      "date": "2026-09-29",
      "company": "meshi",
      "title": "先輩を追うな、先頭に立て",
      "area": "東京",
      "venue": "東京・恵比寿周辺",
      "time": "18:15～20:15",
      "status": "公式",
      "note": "28卒。運営会社の自社採用イベント。",
      "source": "https://app.shachomeshi.com/event-detail/FDHiR6GPCD",
      "host": "社長メシ",
      "id": "evt-019"
    },
    {
      "date": "2026-09-30",
      "company": "meshi",
      "title": "社長直下で20代から、会社をつくる側へ",
      "area": "東京",
      "venue": "東京・渋谷",
      "time": "18:00～20:00",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/XBStF78jHc",
      "host": "スタームービング",
      "id": "evt-020"
    },
    {
      "date": "2026-10-01",
      "company": "meshi",
      "title": "20代で社長になるコツ、人事責任者が伝授",
      "area": "東京",
      "venue": "東京・西麻布",
      "time": "18:30～20:30",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/QjfPaK1syS",
      "host": "FUSIONIA",
      "id": "evt-021"
    },
    {
      "date": "2026-10-01",
      "company": "meshi",
      "title": "前のめりで良い奴、全員集合！",
      "area": "東京",
      "venue": "東京・四ツ谷",
      "time": "19:30～21:30",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/enVGDCN6tl",
      "host": "宮工房",
      "id": "evt-022"
    },
    {
      "date": "2026-10-02",
      "company": "meshi",
      "title": "社長と本音で語る。成長企業の未来とあなたの可能性",
      "area": "東京",
      "venue": "東京・末広町",
      "time": "18:30～20:30",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/Bm0oEVAVcw",
      "host": "J・ART",
      "id": "evt-023"
    },
    {
      "date": "2026-10-03",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "東京",
      "venue": "東京",
      "time": "10:00～14:00／15:30～19:30",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。 直近予約フォームでも時間を確認。事前セミナー等の集合時刻は別途確認。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-024"
    },
    {
      "date": "2026-10-03",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "東京",
      "venue": "東京",
      "time": "11:20～17:20",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-025"
    },
    {
      "date": "2026-10-04",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "福岡",
      "venue": "福岡",
      "time": "11:20～17:00",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-026"
    },
    {
      "date": "2026-10-07",
      "company": "deiba",
      "title": "28卒｜大手内定者が語る ES・面接突破のリアル",
      "area": "未確認",
      "venue": "形式・会場 n.a.",
      "time": "19:00～20:00",
      "status": "公式",
      "note": "",
      "source": "https://deiba.jp/event/event#category2-block1-event6",
      "host": "DEiBA Company",
      "id": "evt-027"
    },
    {
      "date": "2026-10-09",
      "company": "deiba",
      "title": "28卒｜デアイバ式・就活対策講座～面接対策～",
      "area": "未確認",
      "venue": "形式・会場 n.a.",
      "time": "15:00～16:00",
      "status": "公式",
      "note": "",
      "source": "https://deiba.jp/event/event#category2-block1-event7",
      "host": "DEiBA Company",
      "id": "evt-028"
    },
    {
      "date": "2026-10-09",
      "company": "meshi",
      "title": "大阪開催｜学生50名と企業10社で就活メシ",
      "area": "大阪",
      "venue": "大阪・梅田駅周辺",
      "time": "17:00～21:00",
      "status": "公式",
      "note": "全学年。ユナイテッドウィル主催。受付16:30～。",
      "source": "https://app.shachomeshi.com/event-detail/C58BHZcwXq",
      "host": "社長メシ",
      "id": "evt-029"
    },
    {
      "date": "2026-10-09",
      "company": "meshi",
      "title": "起業家志望集まれ｜仲間と共に成功する秘訣は再現性",
      "area": "東京",
      "venue": "東京・浜松町",
      "time": "19:00～21:00",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/e7YDJUgdEk",
      "host": "PassionPlanets",
      "id": "evt-030"
    },
    {
      "date": "2026-10-09",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "東京",
      "venue": "東京",
      "time": "PM（予約フォーム15:30～18:00）",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。 同日東京枠の予約フォーム時間を併記。シリーズ名との対応は申込前確認。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-031"
    },
    {
      "date": "2026-10-10",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "仙台",
      "venue": "仙台",
      "time": "11:20～16:30",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-032"
    },
    {
      "date": "2026-10-10",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "大阪",
      "venue": "大阪・AP大阪茶屋町",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-033"
    },
    {
      "date": "2026-10-10",
      "company": "meshi",
      "title": "大阪開催・28卒限定｜美味しいご飯を食べながら本音で",
      "area": "大阪",
      "venue": "大阪・会場候補複数",
      "time": "18:00～20:00",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/cQpZuumyHz",
      "host": "丸楽紙業",
      "id": "evt-034"
    },
    {
      "date": "2026-10-17",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "大阪",
      "venue": "大阪",
      "time": "11:20～17:20",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-035"
    },
    {
      "date": "2026-10-17",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "東京",
      "venue": "東京・AP渋谷道玄坂11F",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-036"
    },
    {
      "date": "2026-10-17",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "東京",
      "venue": "東京・赤坂ガーデンシティ",
      "time": "10:00～14:00／15:30～19:30",
      "status": "公式",
      "note": "公式年間日程表でArenaと確認。同日のAM・PMは1行に集約。2026-09-17に公開予約フォームで時間・会場を追加確認。事前セミナー等の集合時刻は別途確認。",
      "source": "https://media.jobtv.jp/event/entry?event_area=6ef3c979-5d67-416a-923c-beea79abe703",
      "host": "ジョブTV",
      "id": "evt-037"
    },
    {
      "date": "2026-10-18",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "東京",
      "venue": "東京",
      "time": "11:20～17:20",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-038"
    },
    {
      "date": "2026-10-19",
      "company": "meshi",
      "title": "AIでの課題解決にこだわる IT社長メシIN池袋",
      "area": "東京",
      "venue": "東京・池袋",
      "time": "19:00～20:00",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/XKqf0OmMrf",
      "host": "ウィナス",
      "id": "evt-039"
    },
    {
      "date": "2026-10-19",
      "company": "meshi",
      "title": "日本から売れないセールスパーソンをゼロにする",
      "area": "東京",
      "venue": "東京・浜松町・田町・三田",
      "time": "19:00～21:00",
      "status": "他社主催",
      "note": "依頼対象の運営会社が主催するイベントとは区別。公開一覧の日本時間表示。タイトル一部短縮。",
      "source": "https://app.shachomeshi.com/event-detail/gtrMKcUWof",
      "host": "キーレイズ",
      "id": "evt-040"
    },
    {
      "date": "2026-10-23",
      "company": "jobtv",
      "title": "JOBTV Summit",
      "area": "東京",
      "venue": "東京",
      "time": "PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-041"
    },
    {
      "date": "2026-10-24",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "大阪",
      "venue": "大阪",
      "time": "10:00～14:00／15:30～19:30",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。 直近予約フォームでも時間を確認。事前セミナー等の集合時刻は別途確認。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-042"
    },
    {
      "date": "2026-10-24",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "東京",
      "venue": "東京",
      "time": "11:20～17:20",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-043"
    },
    {
      "date": "2026-10-24",
      "company": "cheer",
      "title": "チアフェス",
      "area": "東京",
      "venue": "東京",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-044"
    },
    {
      "date": "2026-10-24",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "福岡",
      "venue": "福岡・ヒューリックスクエア福岡天神",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-045"
    },
    {
      "date": "2026-10-25",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "札幌",
      "venue": "札幌",
      "time": "11:20～17:00",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-046"
    },
    {
      "date": "2026-10-27",
      "company": "meshi",
      "title": "就活メシMEGA～人生を変える食卓の記録～",
      "area": "東京",
      "venue": "東京・渋谷周辺",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "全学年。日本時間の公開画面で確認。",
      "source": "https://app.shachomeshi.com/event-detail/M6xYEASlpq",
      "host": "社長メシ",
      "id": "evt-047"
    },
    {
      "date": "2026-10-27",
      "company": "talent",
      "title": "Talent Labo｜オンライン・少人数座談会",
      "area": "オンライン",
      "venue": "Zoom",
      "time": "15:00～17:00",
      "status": "公式",
      "note": "28卒限定。受付 14:45～。公式LPおよび参加希望日程フォームで確認。",
      "source": "https://talentlabo.jp/form.html",
      "host": "Talent Labo（ご指定：オルディナパートナーズ）",
      "id": "evt-048"
    },
    {
      "date": "2026-10-29",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "東京",
      "venue": "東京",
      "time": "PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-049"
    },
    {
      "date": "2026-10-31",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "広島",
      "venue": "広島",
      "time": "11:20～17:00",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-050"
    },
    {
      "date": "2026-11-01",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "岡山",
      "venue": "岡山",
      "time": "11:20～17:00",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-051"
    },
    {
      "date": "2026-11-01",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "名古屋",
      "venue": "名古屋・ABOホール",
      "time": "12:00～17:00",
      "status": "公式",
      "note": "28卒。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-052"
    },
    {
      "date": "2026-11-07",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-053"
    },
    {
      "date": "2026-11-07",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-054"
    },
    {
      "date": "2026-11-08",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "大阪",
      "venue": "大阪",
      "time": "11:20～17:20",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-055"
    },
    {
      "date": "2026-11-11",
      "company": "jobtv",
      "title": "JOBTV Summit",
      "area": "東京",
      "venue": "東京",
      "time": "PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-056"
    },
    {
      "date": "2026-11-14",
      "company": "deiba",
      "title": "デアイバ（スカウト型イベント）",
      "area": "金沢",
      "venue": "金沢",
      "time": "11:20～17:00",
      "status": "公式",
      "note": "28卒。終了時刻は主催者ページを優先。",
      "source": "https://deiba.jp/event/event",
      "host": "DEiBA Company",
      "id": "evt-057"
    },
    {
      "date": "2026-11-14",
      "company": "cheer",
      "title": "チアフェス",
      "area": "大阪",
      "venue": "大阪",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-058"
    },
    {
      "date": "2026-11-14",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "大阪",
      "venue": "大阪・AP大阪茶屋町",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-059"
    },
    {
      "date": "2026-11-14",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "東京",
      "venue": "東京・渋谷クロスタワー24F",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-060"
    },
    {
      "date": "2026-11-14",
      "company": "talent",
      "title": "Talent Labo｜オンライン・少人数座談会",
      "area": "オンライン",
      "venue": "Zoom",
      "time": "15:00～17:00",
      "status": "公式",
      "note": "28卒限定。受付 14:45～。公式LPおよび参加希望日程フォームで確認。",
      "source": "https://talentlabo.jp/form.html",
      "host": "Talent Labo（ご指定：オルディナパートナーズ）",
      "id": "evt-061"
    },
    {
      "date": "2026-11-14",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-062"
    },
    {
      "date": "2026-11-15",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-063"
    },
    {
      "date": "2026-11-20",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "東京",
      "venue": "東京",
      "time": "PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-064"
    },
    {
      "date": "2026-11-21",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-065"
    },
    {
      "date": "2026-11-22",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "福岡",
      "venue": "福岡・ヒューリックスクエア福岡天神",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-066"
    },
    {
      "date": "2026-11-22",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "名古屋",
      "venue": "名古屋",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-067"
    },
    {
      "date": "2026-11-28",
      "company": "cheer",
      "title": "チアフェス",
      "area": "東京",
      "venue": "東京",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-068"
    },
    {
      "date": "2026-11-28",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-069"
    },
    {
      "date": "2026-11-28",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "大阪",
      "venue": "大阪",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-070"
    },
    {
      "date": "2026-11-29",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-071"
    },
    {
      "date": "2026-11-30",
      "company": "meshi",
      "title": "GRIT就活2028",
      "area": "東京",
      "venue": "東京・ベルサール渋谷ガーデン",
      "time": "13:00～18:00",
      "status": "他社主催",
      "note": "Maenomery主催。社長メシ掲載本文に曜日不整合あり。主催者LPの日付（2026/11/30・月）を優先。参加前に再確認。",
      "source": "https://event.maenomery.jp/",
      "host": "Maenomery",
      "id": "evt-072"
    },
    {
      "date": "2026-12-05",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-073"
    },
    {
      "date": "2026-12-05",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-074"
    },
    {
      "date": "2026-12-05",
      "company": "shabell",
      "title": "しゃべる就活フェスタ",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "公式",
      "note": "主催者発表で日程確認。",
      "source": "https://prtimes.jp/main/html/rd/p/000000023.000082450.html",
      "host": "しゃべる（shabell）",
      "id": "evt-075"
    },
    {
      "date": "2026-12-12",
      "company": "cheer",
      "title": "チアフェス",
      "area": "東京",
      "venue": "東京",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-076"
    },
    {
      "date": "2026-12-12",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "大阪",
      "venue": "大阪・AP大阪梅田東",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-077"
    },
    {
      "date": "2026-12-12",
      "company": "talent",
      "title": "Talent Labo｜対面・少人数座談会",
      "area": "東京",
      "venue": "東京都渋谷区円山町3-6 E・スペースタワー6F",
      "time": "14:00～17:30",
      "status": "公式",
      "note": "28卒限定。受付 13:30～。公式LPおよび参加希望日程フォームで確認。",
      "source": "https://talentlabo.jp/form.html",
      "host": "Talent Labo（ご指定：オルディナパートナーズ）",
      "id": "evt-078"
    },
    {
      "date": "2026-12-12",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "大阪",
      "venue": "大阪",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-079"
    },
    {
      "date": "2026-12-12",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-080"
    },
    {
      "date": "2026-12-12",
      "company": "jobtv",
      "title": "JOBTV Fes",
      "area": "東京",
      "venue": "東京",
      "time": "終日",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-081"
    },
    {
      "date": "2026-12-13",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "大阪",
      "venue": "大阪",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-082"
    },
    {
      "date": "2026-12-19",
      "company": "cheer",
      "title": "チアフェス",
      "area": "大阪",
      "venue": "大阪",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-083"
    },
    {
      "date": "2026-12-19",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "福岡",
      "venue": "福岡・ヒューリックスクエア福岡天神",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-084"
    },
    {
      "date": "2026-12-19",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-085"
    },
    {
      "date": "2026-12-19",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-086"
    },
    {
      "date": "2026-12-20",
      "company": "jobtv",
      "title": "JOBTV Summit",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-087"
    },
    {
      "date": "2027-01-07",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-088"
    },
    {
      "date": "2027-01-09",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-089"
    },
    {
      "date": "2027-01-11",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "大阪",
      "venue": "大阪",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-090"
    },
    {
      "date": "2027-01-13",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "東京",
      "venue": "東京",
      "time": "AM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-091"
    },
    {
      "date": "2027-01-15",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "東京",
      "venue": "東京",
      "time": "PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-092"
    },
    {
      "date": "2027-01-16",
      "company": "cheer",
      "title": "チアフェス",
      "area": "東京",
      "venue": "東京",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-093"
    },
    {
      "date": "2027-01-16",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-094"
    },
    {
      "date": "2027-01-17",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "福岡",
      "venue": "福岡",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-095"
    },
    {
      "date": "2027-01-23",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "大阪",
      "venue": "大阪・AP大阪梅田東",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-096"
    },
    {
      "date": "2027-01-24",
      "company": "deiba",
      "title": "デアイバ（日付・曜日不整合）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "要確認",
      "note": "原表1/24(土)、1/25(日)。2027年の暦は日曜・月曜。正しい開催日を確定できないため参考扱い。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-097"
    },
    {
      "date": "2027-01-25",
      "company": "deiba",
      "title": "デアイバ（日付・曜日不整合）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "要確認",
      "note": "原表1/24(土)、1/25(日)。2027年の暦は日曜・月曜。正しい開催日を確定できないため参考扱い。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-098"
    },
    {
      "date": "2027-01-30",
      "company": "cheer",
      "title": "チアフェス",
      "area": "大阪",
      "venue": "大阪",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-099"
    },
    {
      "date": "2027-01-30",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "東京",
      "venue": "東京・AP渋谷道玄坂11F",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-100"
    },
    {
      "date": "2027-02-02",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-101"
    },
    {
      "date": "2027-02-04",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-102"
    },
    {
      "date": "2027-02-06",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-103"
    },
    {
      "date": "2027-02-06",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-104"
    },
    {
      "date": "2027-02-09",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-105"
    },
    {
      "date": "2027-02-10",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "大阪",
      "venue": "大阪",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-106"
    },
    {
      "date": "2027-02-11",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "大阪",
      "venue": "大阪",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-107"
    },
    {
      "date": "2027-02-13",
      "company": "cheer",
      "title": "チアフェス",
      "area": "東京",
      "venue": "東京",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-108"
    },
    {
      "date": "2027-02-13",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "名古屋",
      "venue": "名古屋",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-109"
    },
    {
      "date": "2027-02-16",
      "company": "jobtv",
      "title": "JOBTV Arena",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-110"
    },
    {
      "date": "2027-02-17",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "福岡",
      "venue": "福岡・ヒューリックスクエア福岡天神",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-111"
    },
    {
      "date": "2027-02-19",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-112"
    },
    {
      "date": "2027-02-20",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "東京",
      "venue": "東京・AP渋谷道玄坂11F",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-113"
    },
    {
      "date": "2027-02-20",
      "company": "talent",
      "title": "Talent Labo｜対面・少人数座談会",
      "area": "東京",
      "venue": "東京都渋谷区円山町3-6 E・スペースタワー6F",
      "time": "14:00～17:30",
      "status": "公式",
      "note": "28卒限定。受付 13:30～。公式LPおよび参加希望日程フォームで確認。",
      "source": "https://talentlabo.jp/form.html",
      "host": "Talent Labo（ご指定：オルディナパートナーズ）",
      "id": "evt-114"
    },
    {
      "date": "2027-02-20",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-115"
    },
    {
      "date": "2027-02-21",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-116"
    },
    {
      "date": "2027-02-24",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-117"
    },
    {
      "date": "2027-02-26",
      "company": "jobtv",
      "title": "JOBTV Draft",
      "area": "東京",
      "venue": "東京",
      "time": "AM・PM",
      "status": "公式",
      "note": "公式年間日程表。同日のAM・PMは1行に集約。",
      "source": "https://media.jobtv.jp/service/recruitment-event",
      "host": "ジョブTV",
      "id": "evt-118"
    },
    {
      "date": "2027-02-27",
      "company": "cheer",
      "title": "チアフェス",
      "area": "大阪",
      "venue": "大阪",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-119"
    },
    {
      "date": "2027-02-27",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-120"
    },
    {
      "date": "2027-02-27",
      "company": "shabell",
      "title": "しゃべる就活フェスタ",
      "area": "大阪",
      "venue": "大阪",
      "time": "n.a.",
      "status": "公式",
      "note": "主催者発表で日程確認。",
      "source": "https://prtimes.jp/main/html/rd/p/000000023.000082450.html",
      "host": "しゃべる（shabell）",
      "id": "evt-121"
    },
    {
      "date": "2027-02-28",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "大阪",
      "venue": "大阪",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-122"
    },
    {
      "date": "2027-03-06",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "東京",
      "venue": "東京・渋谷・名取ビル5F",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-123"
    },
    {
      "date": "2027-03-07",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-124"
    },
    {
      "date": "2027-03-13",
      "company": "cheer",
      "title": "チアフェス",
      "area": "東京",
      "venue": "東京",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-125"
    },
    {
      "date": "2027-03-13",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "大阪",
      "venue": "大阪・AP大阪茶屋町",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-126"
    },
    {
      "date": "2027-03-14",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "大阪",
      "venue": "大阪",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-127"
    },
    {
      "date": "2027-03-17",
      "company": "shabell",
      "title": "しゃべる就活",
      "area": "福岡",
      "venue": "福岡・ヒューリックスクエア福岡天神",
      "time": "13:00～18:00",
      "status": "公式",
      "note": "28卒向け日程。旧27卒欄は除外。",
      "source": "https://event.shabell.co.jp/",
      "host": "しゃべる（shabell）",
      "id": "evt-128"
    },
    {
      "date": "2027-03-20",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-129"
    },
    {
      "date": "2027-03-27",
      "company": "cheer",
      "title": "チアフェス",
      "area": "大阪",
      "venue": "大阪",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-130"
    },
    {
      "date": "2027-03-27",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-131"
    },
    {
      "date": "2027-03-28",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "大阪",
      "venue": "大阪",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-132"
    },
    {
      "date": "2027-04-10",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-133"
    },
    {
      "date": "2027-04-17",
      "company": "cheer",
      "title": "チアフェス",
      "area": "東京",
      "venue": "東京",
      "time": "12:20～17:00",
      "status": "公式",
      "note": "28卒。9/26東京は南青山2-11-16 9F、その他の会場詳細は確認時点未定。",
      "source": "https://cheercareer.jp/lp/cheer_fes",
      "host": "チアキャリア",
      "id": "evt-134"
    },
    {
      "date": "2027-04-17",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-135"
    },
    {
      "date": "2027-04-18",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "大阪",
      "venue": "大阪",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-136"
    },
    {
      "date": "2027-04-24",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-137"
    },
    {
      "date": "2027-05-08",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-138"
    },
    {
      "date": "2027-05-22",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-139"
    },
    {
      "date": "2027-06-05",
      "company": "deiba",
      "title": "デアイバ（参考日程）",
      "area": "東京",
      "venue": "東京",
      "time": "n.a.",
      "status": "二次情報",
      "note": "ネオキャリア掲載。主催者の公開日程では個別照合できず、開催・募集状況は要確認。",
      "source": "https://www.neo-career.co.jp/humanresource/deainoba/",
      "host": "DEiBA Company",
      "id": "evt-140"
    }
  ]
};
